/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AddItemTable: typeof import("./components/common/addItemTable.vue")["default"];
    ElAside: typeof import("element-plus/es")["ElAside"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElButton: typeof import("element-plus/es")["ElButton"];
    ElCard: typeof import("element-plus/es")["ElCard"];
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"];
    ElCheckboxGroup: typeof import("element-plus/es")["ElCheckboxGroup"];
    ElCion: typeof import("element-plus/es")["ElCion"];
    ElContainer: typeof import("element-plus/es")["ElContainer"];
    ElDatePicker: typeof import("element-plus/es")["ElDatePicker"];
    ElDialog: typeof import("element-plus/es")["ElDialog"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElForm: typeof import("element-plus/es")["ElForm"];
    ElFormItem: typeof import("element-plus/es")["ElFormItem"];
    ElHeader: typeof import("element-plus/es")["ElHeader"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElImage: typeof import("element-plus/es")["ElImage"];
    ElInput: typeof import("element-plus/es")["ElInput"];
    ElMain: typeof import("element-plus/es")["ElMain"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
    ElOption: typeof import("element-plus/es")["ElOption"];
    ElPagination: typeof import("element-plus/es")["ElPagination"];
    ElRadio: typeof import("element-plus/es")["ElRadio"];
    ElRadioButton: typeof import("element-plus/es")["ElRadioButton"];
    ElRadioGroup: typeof import("element-plus/es")["ElRadioGroup"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSelect: typeof import("element-plus/es")["ElSelect"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTable: typeof import("element-plus/es")["ElTable"];
    ElTableColumn: typeof import("element-plus/es")["ElTableColumn"];
    ElTag: typeof import("element-plus/es")["ElTag"];
    ElTree: typeof import("element-plus/es")["ElTree"];
    ElUpload: typeof import("element-plus/es")["ElUpload"];
    IEpEdit: typeof import("~icons/ep/edit")["default"];
    IEpHide: typeof import("~icons/ep/hide")["default"];
    IEpHome: typeof import("~icons/ep/home")["default"];
    IEpHomeFilled: typeof import("~icons/ep/home-filled")["default"];
    IEpUser: typeof import("~icons/ep/user")["default"];
    IEpUserFilled: typeof import("~icons/ep/user-filled")["default"];
    IEpView: typeof import("~icons/ep/view")["default"];
    MyForm: typeof import("./components/common/MyForm.vue")["default"];
    MyUpload: typeof import("./components/common/MyUpload.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    SvgIcon: typeof import("./components/common/SvgIcon.vue")["default"];
    TreeTable: typeof import("./components/common/TreeTable.vue")["default"];
  }
}
